-- Transactions table
-- Stores payment transactions for contracts and subscriptions

CREATE TABLE transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id) ON DELETE CASCADE,
    rental_company_id UUID NOT NULL REFERENCES rental_companies(id) ON DELETE CASCADE,
    customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
    
    -- Transaction details
    transaction_type transaction_type NOT NULL DEFAULT 'rental_payment',
    payment_method payment_method NOT NULL,
    status transaction_status NOT NULL DEFAULT 'pending',
    
    -- Amounts
    amount DECIMAL(10, 2) NOT NULL CHECK (amount > 0),
    
    -- Safe2Pay integration
    safe2pay_transaction_id TEXT, -- Safe2Pay transaction ID
    safe2pay_payment_url TEXT, -- Payment URL (for boleto/pix)
    safe2pay_barcode TEXT, -- Boleto barcode
    safe2pay_pix_qrcode TEXT, -- PIX QR code
    safe2pay_response JSONB, -- Full Safe2Pay response
    
    -- Dates
    due_date DATE NOT NULL,
    paid_at TIMESTAMPTZ,
    
    -- Additional info
    description TEXT,
    reference_month INTEGER CHECK (reference_month >= 1 AND reference_month <= 12), -- Month reference (1-12)
    reference_year INTEGER CHECK (reference_year >= 2024), -- Year reference
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_transactions_contract_id ON transactions(contract_id);
CREATE INDEX idx_transactions_rental_company_id ON transactions(rental_company_id);
CREATE INDEX idx_transactions_customer_id ON transactions(customer_id);
CREATE INDEX idx_transactions_status ON transactions(status);
CREATE INDEX idx_transactions_due_date ON transactions(due_date);
CREATE INDEX idx_transactions_safe2pay_transaction_id ON transactions(safe2pay_transaction_id);
CREATE INDEX idx_transactions_reference ON transactions(reference_year, reference_month);

-- Trigger for updated_at
CREATE TRIGGER update_transactions_updated_at
    BEFORE UPDATE ON transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Rental companies can view their own transactions
CREATE POLICY "Rental companies can view their own transactions"
    ON public.transactions
    FOR SELECT
    TO authenticated
    USING (
        rental_company_id = auth.uid()
    );

-- Rental companies can insert their own transactions
CREATE POLICY "Rental companies can insert their own transactions"
    ON public.transactions
    FOR INSERT
    TO authenticated
    WITH CHECK (
        rental_company_id = auth.uid()
    );

-- Rental companies can update their own transactions
CREATE POLICY "Rental companies can update their own transactions"
    ON public.transactions
    FOR UPDATE
    TO authenticated
    USING (
        rental_company_id = auth.uid()
    );

-- Customers can view their own transactions
CREATE POLICY "Customers can view their own transactions"
    ON public.transactions
    FOR SELECT
    TO authenticated
    USING (
        customer_id = auth.uid()
    );

-- Platform admins can view all transactions
CREATE POLICY "Platform admins can view all transactions"
    ON public.transactions
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.platform_admins
            WHERE id = auth.uid()
        )
    );

-- Comments
COMMENT ON TABLE transactions IS 'Payment transactions for contracts and platform subscriptions';
COMMENT ON COLUMN transactions.safe2pay_transaction_id IS 'Safe2Pay transaction ID for tracking';
COMMENT ON COLUMN transactions.safe2pay_payment_url IS 'Payment URL generated by Safe2Pay (boleto/pix)';
COMMENT ON COLUMN transactions.safe2pay_response IS 'Complete Safe2Pay API response for debugging';
COMMENT ON COLUMN transactions.reference_month IS 'Month reference for rental payments (1-12)';
COMMENT ON COLUMN transactions.reference_year IS 'Year reference for rental payments';

-- Function to auto-generate transactions for active contracts
-- This will be called by a cron job or edge function
CREATE OR REPLACE FUNCTION public.generate_monthly_transactions()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    contract_record RECORD;
    transaction_count INTEGER := 0;
    current_month INTEGER;
    current_year INTEGER;
    transaction_due_date DATE;
BEGIN
    -- Get current month and year
    current_month := EXTRACT(MONTH FROM NOW());
    current_year := EXTRACT(YEAR FROM NOW());
    
    -- Loop through active contracts
    FOR contract_record IN 
        SELECT 
            c.id,
            c.rental_company_id,
            c.customer_id,
            c.monthly_value,
            c.payment_day
        FROM public.contracts c
        WHERE 
            c.status = 'active'
            AND (c.end_date IS NULL OR c.end_date >= CURRENT_DATE)
            -- Check if transaction for this month doesn't exist yet
            AND NOT EXISTS (
                SELECT 1 FROM public.transactions t
                WHERE 
                    t.contract_id = c.id
                    AND t.reference_month = current_month
                    AND t.reference_year = current_year
            )
    LOOP
        -- Calculate due date (payment_day of current month)
        transaction_due_date := make_date(
            current_year, 
            current_month, 
            LEAST(contract_record.payment_day, 28) -- Ensure valid day
        );
        
        -- Create transaction
        INSERT INTO public.transactions (
            contract_id,
            rental_company_id,
            customer_id,
            transaction_type,
            payment_method,
            status,
            amount,
            due_date,
            description,
            reference_month,
            reference_year
        ) VALUES (
            contract_record.id,
            contract_record.rental_company_id,
            contract_record.customer_id,
            'rental_payment',
            'boleto', -- Default payment method
            'pending',
            contract_record.monthly_value,
            transaction_due_date,
            'Mensalidade de aluguel - ' || TO_CHAR(NOW(), 'Month/YYYY'),
            current_month,
            current_year
        );
        
        transaction_count := transaction_count + 1;
    END LOOP;
    
    RETURN transaction_count;
END;
$$;

COMMENT ON FUNCTION public.generate_monthly_transactions() IS 'Auto-generates monthly transactions for active contracts';

